### PR TITLE
Drop Python < 3.6

### PR DESCRIPTION
**Pull request by greg-hellings**
Drop py27/py35
Begin shifting to pytest
Shift to testing tox externally, rather than in-process

This will impact the coverage % in a decently significant way, as the
calls into the actual hooks will be done in a separate process. I don't
know if it is possible to grab that info with coverage, but I don't know
a simple way.

### CODE REVIEW

**Comment by greg-hellings** [comment]
This is preparation both for the move to including mypy and to ease the process of adding tests for when we tackle #13

**Review by ssbarnea — APPROVED** [review]

**Comment by ssbarnea** [comment]
@greg-hellings Nice! Btw, if you can remove the comment from codecov it would be great. We should have no PR comments from bots, that is why we have checks that can fail.

**Review by ssbarnea — CHANGES_REQUESTED** [review]
Be sure you also update metadata (python_requires).

Also grep for "six", "sys.version" to spot other places.

**Comment by greg-hellings** [comment]
> @greg-hellings Nice! Btw, if you can remove the comment from codecov it would be great. We should have no PR comments from bots, that is why we have checks that can fail.

I can remove the comment, but I don't see a way to disable the bot from posting it again in the future. That might be an organization level thing you would need to take care of?

**Review by ssbarnea — APPROVED** [review]

**Pull request merged**
